PRNDcompany/prnd-android-workflows

.github/workflows/jira_release.yml

workflow를 재사용하기 위한 용도의 repository를 새로 만들고 이곳에 중복되는 workflow들을 모두 옮겨놓을 예정입니다.
가장 먼저 `jira_release.yml` 부터 진행했습니다.
외부로 드러나면 안되는 부분들이 있어서 반영 화면은 아래 PR에서 확인하실 수 있습니다.
https://github.com/PRNDcompany/heydealer-android/pull/4050

HDA-6845 [라이브러리] [workflow 재사용] JIRA release

---

.github/workflows/unit_test.yml

모든 repository에 중복되어있는 단위테스트 workflow를 분리합니다.
personal_access_token만 받아서 checkout 하는 방식으로 변경하였습니다.
각 앱 repository에서는 main 브랜치를 참조하도록 만들어야해서 해당 PR 병합 후 다시 리뷰요청드리겠습니다.
https://github.com/PRNDcompany/heydealer-android/actions/runs/3318369652/jobs/5482813702

HDA-6868 [공통] [workflow 재사용] 단위 테스트

---

.github/workflows/release_tag.yml

재사용할 수 있는 release, tag 생성하는 workflow를 추가합니다.
`GITHUB_TOKEN`은 예약어여서 `GITHUB_AUTH_TOKEN`을 통해서 token을 받도록 만들었습니다.
이 workflow를 통해서 만들어진 tag, release는 모두 제거했습니다.
https://github.com/PRNDcompany/heydealer-android/actions/runs/3367027271

HDA-6869 [공통] [workflow 재사용] release, tag 생성

---

.github/workflows/unit_test.yml

actions/checkout Action에서 이미 clean을 하고 있기 때문에 불필요한 작업이어서 제거합니다.

HDA-6974 [공통] 단위테스트에서 clean 제거

---

.github/workflows/jira_release.yml
.github/workflows/release_pr_create.yml
.github/workflows/release_pr_update.yml
.github/workflows/release_tag.yml
.github/workflows/unit_test.yml

공식 문서에 명확하게 나와있는건 없지만 Github Action에서 secrets은 SCREAMING_SNAKE_CASE가 사실상 표준으로 보여서 모두 수정했습니다.
추가로 GITHUB_TOKEN이 secrets로 그대로 넘어오고 있어서 불필요하게 GITHUB_AUTH_TOKEN을 넘기고 사용하는 부분들을 모두 제거했습니다.

HDA-6975 [공통] [workflow 재사용] secrets 변수 이름들을 컨벤션에 따라 SCREAMING_SNAKE_CASE로 변경

---

.github/workflows/release_pr_update.yml

최초에 만들 때, 외부에서 main, master인지를 받고 처리해야 했는데 master로 고정되어 있었습니다.
앞으로 master를 쓰지 않을 예정이니 main 브랜치로 고정합니다.

HDA-7438 [공통] master 브랜치를 main 브랜치로 전환

---

.github/workflows/build_debug_app.yml

debug 빌드를 수행하는 workflow를 추가합니다.
cache까지 처리하는 setup-java까지 추가하려다가 캐시 처리를 제대로 하려면 꽤나 복잡해서 일단은 제거해두었습니다.
현재 사용중인 `Android` runner에 영향이 가지 않도록 임시로 사용할 `migration` runner는 각 앱 repository에 하나씩 만들어두었습니다.

HDA-7432 [공통][GitHub Action 마이그레이션] debug 빌드

---

.github/workflows/build_app.yml
.github/workflows/unit_test.yml

GitHub Action에서 concurrency group을 같은 group으로 지정하면 동시에 하나만 수행하도록 만들 수 있습니다. 
동시성 그룹은 아래와 같이 설정합니다.
1. workflow 별로 따로따로 체크한다. (단위 테스트, 앱 빌드)
2. PR이면 PR 번호를 기준으로 따로 체크한다.
3. PR이 아니면 refs를 기준으로 따로 체크한다.
새로운 작업이 추가되었을 때, 기존 작업을 계속해서 수행할 필요가 없기 때문에 cancel-in-progress를 true로 처리합니다.
https://github.com/PRNDcompany/heydealer-call-android/actions/runs/4101503008

HDA-8054 [공통][GitHub Action 마이그레이션 2차] 기존 작업이 끝나지 않은 상태에서 새로운 작업이 시작되면 이전 작업 취소

---

.github/workflows/release_pr_create.yml

- PR을 자동으로 만들어 줄때 assignee를 마지막 커밋한 author의 정보로 지정하고 있음
- branch를 자동으로 만들어주는 작업을 하는 작업을 하게 된다면 author는 Github Actions가 되는데 유효하지 않은 assignee가 되어서 오류가 발생함
- 꼭 assignee를 지정해줄 필요도 없기 때문에 해당 파라미터 제거

HDA-8840 [공통] [GitHub Action] release_pr_create 에서 pr_assignee 제거

---

.github/workflows/release_pr_develop_merge.yml

develop 브랜치를 target으로 하는 PR을 자동으로 병합하는 workflow를 추가합니다.
추가로 기존에 실패했던 것까지 해결해두었습니다.
기존에 실패하던 이유는 branch protection rule에서 최소 하나의 Approve가 필요해서 실패했습니다.
따라서 자동으로 Approve를 한 다음 Merge를 하면 성공합니다.
- https://github.com/olaf-prnd/workflow-test/pull/9
- https://github.com/olaf-prnd/workflow-test/pull/10
- [develop PR 자동 병합 workflow 실행결과](https://github.com/olaf-prnd/workflow-test/pull/10/checks)

HDA-6873 [공통] [workflow 재사용] develop PR 병합

---

.github/workflows/build_app.yml

SigningConfig에 관련된 속성들을 GitHub Secret으로 관리하기 위한 작업입니다.
먼저 모든 프로젝트가 각각 자신의 signing config에 해당하는 secret을 등록해야 합니다.
- Base64 인코딩된 keystore 파일
- signing name
- signing password
이렇게 등록된 name과 password는 GitHub Action의 secret을 통해 가져올 수 있습니다.
keystore 파일은 Base64로 인코딩되었기 때문에 다시 디코딩 과정을 거친 후에 사용할 수 있어서 디코딩 과정을 거쳐 `_temp` 디렉토리에 저장됩니다.
- [실행 결과](https://github.com/PRNDcompany/heydealer-inspector-android/actions/runs/5221248044/jobs/9425283632)

HDA-9313 [공통] SigningConfig를 GitHub Secret으로 관리

---

.github/workflows/build_app.yml

gradle user home을 각 runner별로 사용하도록 만들었습니다.
위치가 `runner/_work/repo_name/repo_name` 이기 때문에 gradle user home은 `../../../.gradle`로 설정하여 `runner/.gradle`에 만들었습니다.

HDA-9311 [공통] runner마다 각각 다른 GRADLE_USER_HOME을 가지도록 설정

---

.github/workflows/build_app.yml

이전 방식으로 빌드가 잘되어서 몰랐는데 3가지 오류가 있었습니다. 😓 
기존에 PATH로 `$RUNNER_TEMP/keystore`를 넘기고 있었는데 상대경로로 처리되어서 잘못된 경로로 keystore 파일을 가져오고 있었습니다.
base64 명령어의 -i 옵션은 input file을 의미합니다.
```
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
-i, --input    input file (default: "-" for stdin)
-o, --output   output file (default: "-" for stdout)
```
기존에는 input 매개변수로 직렬화된 문자열 자체를 넣었는데 그로 인해 잘못 디코딩되고 있었습니다.
secret 매개변수로 호출하는 workflow로부터 넘겨받아야하는데 이를 누락해서 빈 값을 쓰고 있었습니다.
지금까지 debug 빌드는 성공했던 이유가 빈 값이 들어가기 때문이었습니다.
- https://github.com/PRNDcompany/heydealer-android/actions/runs/5553611911/jobs/10142394239?pr=5586
- https://github.com/PRNDcompany/heydealer-for-dealer-android/actions/runs/5553614130/jobs/10142422252?pr=2803

HDA-9655 [공통] Signing 오류 수정

---

.github/workflows/jira_release.yml
.github/workflows/release_pr_create.yml
.github/workflows/release_pr_develop_merge.yml
.github/workflows/release_pr_update.yml
.github/workflows/release_tag.yml

2023년 6월 1일에 이미 지원 종료할 예정이었는데 사용하는 사람이 너무 많아서 연기했습니다. ([공식발표](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
지원 종료 일자가 지났으므로 언제 종료할지 모르니 미리 변경해둡니다.
-----
A workflow using save-state or set-output like the following
```yaml
- name: Save state
run: echo "::save-state name={name}::{value}"
- name: Set output
run: echo "::set-output name={name}::{value}"
```
should be updated to write to the new GITHUB_STATE and GITHUB_OUTPUT environment files:
```yaml
- name: Save state
run: echo "{name}={value}" >> $GITHUB_STATE
- name: Set output
run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

HDA-9676 [공통] GitHub Action set-output 마이그레이션

---

.github/workflows/jira_release.yml
.github/workflows/release_pr_create.yml
.github/workflows/release_pr_develop_merge.yml
.github/workflows/release_pr_update.yml
.github/workflows/release_tag.yml

새로운 방식에 맞춰서 GITHUB_OUTPUT을 마이그레이션하면서 기존 방식과 다르게 변수 값 자체에 특정 문자로 인해 제대로 output이 등록되지 않는 이슈가 있습니다.
다른 방법을 여러가지 시도해보아야 하기 때문에 일단은 모두 정상적으로 동작하는 방식으로 Revert 합니다.

Revert "HDA-9676 [공통] GitHub Action set-output 마이그레이션" [skip-ci]

---

.github/workflows/check_skip.yml

[이전](https://github.com/PRNDcompany/prnd-android-workflows/commit/155662057946bcfc936122afc5f3f39ab539aa81)에 `skip-ci`를 붙이는 대신에 draft PR을 만들기로 해서 제목에 `skip-ci`가 있어도 빌드가 되도록 만들었습니다.
그런데 github action workflow을 건드리는 것이나 README.md와 같이 앱 빌드와는 관계가 없는 PR도 merge를 하려면 결국 draft 상태를 풀어야하기 때문에 앱 빌드가 발생해버려서 불필요하게 자원을 쓰게 됩니다.
이 이슈를 막기 위해서 기존처럼 PR 제목에 `skip-ci`를 붙이면 앱을 빌드하지 않도록 만듭니다.
| draft | skip-ci | draft, skip-ci 둘 다 아닐 때 |
|-|-|-|
| ![draft](https://github.com/PRNDcompany/prnd-android-workflows/assets/85473945/73d49e54-569e-41c2-ad34-a44199b0a6c2) | ![skip-ci](https://github.com/PRNDcompany/prnd-android-workflows/assets/85473945/9ecf0a61-4d21-45f5-a95b-90f4efba406c) | ![draft, skip-ci 둘 다 아닐 때](https://github.com/PRNDcompany/prnd-android-workflows/assets/85473945/7a6caee9-644b-4c2c-a53c-546 …

HDA-8940 [공통] PR 제목에 skip-ci 가 있으면 무시

---

.github/workflows/release_pr_develop_merge.yml

develop PR을 GitHub Action이 자동으로 만들도록 해두었는데 이 때문에 GitHub Action이 만든 PR을 GitHub Action이 Approve 할 수 없습니다.
이를 해결하기 위해 외부에서 별도로 Approve만 하기위한 용도의 `REVIEWER_ACCESS_TOKEN`을 받습니다.
https://prnd.slack.com/archives/C9UERACB1/p1686318743793699
https://github.com/olaf-prnd/workflow-test/pull/39/checks

HDA-9367 [공통] develop PR 자동 병합 workflow 수정

---

.github/workflows/jira_release.yml
.github/workflows/release_pr_create.yml
.github/workflows/release_pr_develop_merge.yml
.github/workflows/release_pr_update.yml
.github/workflows/release_tag.yml

[이전](https://github.com/PRNDcompany/prnd-android-workflows/pull/32) 작업을 그대로 cherry-pick 한 뒤에 [오류만 수정한 commit](https://github.com/PRNDcompany/prnd-android-workflows/commit/975582414301161fb49addef46a62057ca42e3c0)을 추가했습니다.
변경된 방식에서는 버전이 2개 추출되고 있었습니다.
예를 들어, 이전 명령어에서 commit message만 변경하면 아래의 명령어가 만들어집니다.
```sh
echo "version=$(echo 'Merge pull request #5632 from PRNDcompany/release/6.17.0
Release 6.17.0' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_OUTPUT
```
위의 명령어에서 version을 GITHUB_OUTPUT에 넣는 것만 빼고 그대로 터미널에서 실행해보면 버전이 2번 반환된다는걸 바로 알 수 있습니다.
```sh
echo 'Merge pull request #5632 from PRNDcompany/release/6.17.0
Release 6.17.0' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
6.17.0
6.17.0
```
실패하는 경우는 모두 버전이 2개 포함된 commit message를 이용해 버전을 추출하는 경우에 실패하고 GITHUB_REF를 활용하는 경우에는 …

HDA-9785 [공통] GITHUB_OUTPUT 마이그레이션 2차

---

.github/workflows/release_pr_create.yml
.github/workflows/release_pr_develop_merge.yml

github-actions가 만드는 PR은 workflow event를 트리거하지 않습니다. 
이를 해결하기 위해 별도 계정으로 PR을 생성하도록 변경합니다.
이 작업 이후로 아래와 같이 변경됩니다.
- as-is
- PR Create: github-actions
- PR Approve: 별도 계정
- to-be
- PR Create: 별도 계정
- PR Approve:  github-actions
https://prnd.slack.com/archives/C9UERACB1/p1693969335067949

HDA-10071 [공통] GitHub Action을 통해 PR을 만들어도 앱을 빌드하도록 개선

---

.github/workflows/build_app.yml
.github/workflows/build_app_by_comment.yml

`build_app_by_comment.yml`을 통해 빌드하면 코멘트를 남긴 해당 PR의 Check와 연동되지 않습니다.
이는 repository에 설정된 base branch의 `issue_comment` 이벤트를 통해 트리거되기 때문입니다.
이를 해결하기 위해 수동으로 GitHub API를 [Check Run](https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28)을 직접 생성하고 업데이트합니다.
- [HDA-10459 feat: PR Comment를 통해 빌드하면 Check Run을 직접 만들고 업데이트한다](https://github.com/PRNDcompany/prnd-android-workflows/commit/fe72f4d9f9ce12c136d7582bd8b4f41466b1180d)
check run과 관련된 job들은 self-hosted runner에서 수행하지 않고 `ubuntu-latest`에서 처리하도록 만들었습니다.
self-hosted runner는 queue가 꽉 차서 모두 돌아가고 있으면 Check 자체가 만들어지지 않을 수 있습니다.
이를 방지하기 위해 코멘트를 통해 빌드를 한 순간부터 Check에 뜨도록 만들었습니다.
- [HDA-10459 feat: checkout할 ref를 외부에서 받는다](https://github.com/PRNDcompany/prnd-android-workflows/commit/e23a01a852a4b233954b5be68f4b652f8d99f591)
- [HDA-10459 feat: …

HDA-10459 [공통][GitHub Action 마이그레이션 3차] 코멘트를 이용한 빌드에서 Check run 생성과 성공 처리

---

.github/workflows/build.yml

- Release APK, Bundle, QA파일을 한번에 다 만들려고 하다보니 OOM 발생
- https://prnd.slack.com/archives/C9UERACB1/p1698394543393149

HDA-10720 [공통] release 빌드하는 workflow 의 gradle task 분리

---

.github/workflows/build.yml
.github/workflows/build_app_by_comment.yml

- QA, Release 빌드일경우, S3의 `tmp/${{ github.repository }}/${{ inputs.ref }}` 폴더에 임시로 apk/aab 파일을 업로드
- 추후 다음 job에서 QA나 Release의 경로에 맞는 곳으로 move처리
1. 빌드후 ouput으로 APK/AAB파일 만들어짐
2. output/files 폴더로 모든 결과물 이동
3. S3의 `tmp/${{ github.repository }}/${{ inputs.ref }}` 경로로 결과물 업로드
- https://prndcompany.atlassian.net/browse/HDA-10747

HDA-10735 [공통][Jenkins -> GitHub Actions 마이그레이션] QA, Release 빌드일 경우 -> S3 임시 폴더에 파일을 업로드

---

.github/workflows/build.yml

- build.yml에서 release빌드에서는 qa빌드하는 작업을 제거하고
- 각 앱에서 release 처리하는 workflow에서 release빌드 완료후 qa빌드를 처리하는 방식의 job으로 분리

HDA-10790 [공통] [workflow] release빌드시 qa빌드 하는 단계 분리

---

.github/workflows/build_app_by_comment.yml

Check를 처음 만들 때, status 값으로 아무것도 넣지 않으면 queued 상태로 생성됩니다.
그러면 실제로 작업을 수행하더라도 계속해서 queued 상태가 되어서 계속 아무 것도 안하는 것으로 오해할 수 있습니다.
실제 상태가 큐에서 대기 중인 경우와 진행 중인 경우 중 작업이 진행중인 경우가 더 많으므로 최초 상태를 in_progress로 생성하도록 변경합니다.

HDA-10827 [공통] Check를 처음 만들 때 in_progress 상태로 생성

---

.github/workflows/build.yml

동시성 그룹을 만들 때, `pull_request.number`에 대한 fallback 값 설정으로 `github.ref`가 먼저 처리됩니다.
그로 인해 항상 develop branch를 대상으로 동시성 그룹이 만들어져서 여러 개의 QA 빌드 트리거가 발생하는 경우 관계없는 PR들이어도 같은 동시성 그룹을 가지게 됩니다.
이는 의도했던 바가 아니므로 최초 의도대로 같은 PR별로 다른 동시성 그룹을 가지도록 fallback 값으로 `issue.number`를 먼저 설정하고 마지막으로 `github.ref`로 설정하도록 변경합니다.
임시로 default branch를 변경하고 2번 `build QA` 코멘트를 남겨 테스트해보았습니다.
https://github.com/PRNDcompany/heydealer-call-android/actions/runs/6873496821

HDA-10902 [공통] build 동시성 그룹을 만들 때, issue 번호를 먼저 찾고 없으면 github.ref를 찾도록 수정

---

.github/workflows/build_qa.yml

파일 이름과 job 이름 등등 모든 곳에서 트리거되는 것에 상관없이 수행하는 것에 초점을 맞춰 이름을 짓고 있습니다.
Check를 만드는 곳에서만 누락되어서 여기도 똑같이 수행하는 것에 초점을 맞춰서 `build-qa`로 변경합니다.

HDA-10897 [공통] QA 빌드 Check 이름 수정

---

.github/workflows/compare_jira_release_by_release_pr.yml

1. Release PR의 commit에서 배포예정인 Jira key를 뽑아온뒤
2. Release에 정의된 배포예정인 Jira이슈와 비교해서
3. 만약 배포예정으로 나와있는데 실제 commit이 없는 Jira key를 가져오고 comment
https://github.com/PRNDcompany/compare-jira-release-issue-by-release-pr
https://github.com/PRNDcompany/heydealer-call-android/pull/354#issuecomment-1837918019

HDA-11091 [workflow] Release에 배포예정인 Jira이슈 검증 

---

.github/workflows/build.yml

- 각 runner의 build폴더가 계속 쌓이고만 있어서 용량을 크게 차지하고 있음
- 모든 빌드에서 clean을 하고 시작해서 용량을 최적화 하도록 한다.

HDA-11139 [workflow] 모든 빌드 시작전에 clean 처리 추가

---

.github/workflows/compare_jira_release_by_release_pr.yml

- release 브랜치뿐만 아니라 hotfix 브랜치에서도 동작하도록 대응된 버전으로 최신화
- https://github.com/PRNDcompany/compare-jira-release-issue-by-release-pr/pull/2

HDA-11378 [공통] compare-jira-release-issue-by-release-pr 버전 최신화

---

.github/workflows/compare_jira_release_by_release_pr.yml

- commit comment에 Jira key가 중간에 있을때도 extract가능하도록 정규식 수정된 버전 반영
- https://github.com/PRNDcompany/compare-jira-release-issue-by-release-pr/pull/3

HDA-11475 [workflow] Release에 배포예정인 Jira이슈 검증 버전 최신화

---

.github/workflows/compare_jira_release_by_release_pr.yml

- 커밋 메세지로부터 JIra key를 못가져오는경우가 있는데
- 모든 커밋메세지를 가져오는지, extract를 잘하는지 파악하기 위해 로그 추가된 버전 사용
- https://github.com/PRNDcompany/compare-jira-release-issue-by-release-pr/pull/4

HDA-11532 [workflow] Release에 배포예정인 Jira이슈 검증 - 로그 남기는 버전 업데이트

---

.github/workflows/compare_jira_release_by_release_pr.yml

- 실제 js파일로 빌드하지않아서 이전 버전들이 반영되지 않고 있었음
- ts → js 로 build까지 되서 반영된 버전 반영
: https://github.com/PRNDcompany/compare-jira-release-issue-by-release-pr/pull/5

HDA-11839 [공통] [workflow] Release에 배포예정인 Jira이슈 검증 - 버전 최신화

---

.github/workflows/release_pr_create.yml

- 현재: 배포시 만들어지는 PR이름이 항상 Release xxx 로 되어 있음
- 변경: release, hotfix branch에 맞게 release xxx 혹은 hotfix xxx 로 표시되도록 변경
1. `GITHUB_REF_NAME` = `release/1.0.0` or `hotfix/1.0/1`
2. `GITHUB_REF_NAME`로부터 앞의 이름을 가져옴
3. PR을 만들때 title에 2번의 값을 사용하여 넣도록 수정
- release 1.0.0
- release 1.0.0 -> develop

HDA-14391 [공통] workflow - Release PR생성시 branch이름에 맞는 PR이름으로 만들어지도록 처리

---

.github/workflows/release_pr_create.yml

hotfix PR은 draft 상태로 만들어지도록 변경합니다.
[repo-sync/pull-request 공식문서](https://github.com/repo-sync/pull-request/tree/v2.12.1?tab=readme-ov-file#advanced-options)
임시 repository에서 테스트해보았습니다.

HDA-14353 [공통] hotfix이면 PR을 draft 상태로 생성

---

.github/workflows/release_pr_develop_ready.yml

main이 base인 PR이 ready for review 상태가 되면 develop이 base인 PR도 ready for review 상태로 변경합니다.
main을 base로 하는 PR에서 ready for review를 눌러서 테스트
- [main PR](https://github.com/PRNDcompany/heydealer-call-android/pull/404)
- [develop PR](https://github.com/PRNDcompany/heydealer-call-android/pull/405)

HDA-14472 [workflow] main PR이 ready 상태가 되면 develop PR도 ready 상태로 변경

---

.github/workflows/build.yml

- release 빌드 할 때 app 모듈 외에 prnd-catalog가 항상 같이 apk, aab가 만들어집니다.
: https://github.com/PRNDcompany/prnd-android-workflows/blob/main/.github/workflows/build.yml
- 실제로는 app 모듈과 관련한 내용만 쓰고 있기 때문에 명시적으로 :app 모듈만 빌드하도록 수정합니다.

HDA-16770 [workflow] release 빌드 할 때 catalog 앱은 bundle 하지 않도록 변경

---

.github/workflows/build_debug.yml
.github/workflows/build_qa.yml
.github/workflows/build_release.yml

- 명확하게 개발/QA/Release 빌드일때 필요한 task가 다르므로 다른 yml로 분리해서 사용되도록 한다.
- Release 빌드의 task를 1개로 합친다. 
: https://prnd.slack.com/archives/C9UERACB1/p1743569087862559
- QA빌드도 Release 빌드할때 한번의 task에서 함께 한다.
- Debug 빌드랑만 관련있는 workflow 생성 
: 기존 build.yml을 그대로 복사한뒤 QA/Release 빌드와 관련있는 step은 제거
- Release 빌드랑만 관련있는 workflow 생성 
: 기존 build.yml을 그대로 복사한뒤 build_type 관련 사용하는 코드 제거
- QA 빌드 과정을 기존 build_qa 파일안에 추가 
: 기존 build.yml을 그대로 복사한뒤 build_type 관련된 코드 제거 ref 를 직접 넣어줌
- release 빌드할때 qa빌드도 한번에 모두 하도록 통합

HDA-16774 [공통] workflow - 개발/QA/Release 빌드 workflow 분리

---

.github/workflows/build_debug.yml
.github/workflows/build_qa.yml
.github/workflows/build_release.yml

- 불필요하게 job의 이름을 build-xxx 로 분리하지 않고 build로만 통일
- 여러 Repository에서 check의 이름과 관련된것들이 build 이름을 바라보고 있는데 구지 분리할 필요 없으므로 통일

HDA-16794 [공통] workflow - 빌드관련 job의 이름을 모두 build로 통일

---

.github/workflows/build_qa.yml
.github/workflows/build_release.yml

- QA/Release 빌드는 self host runner가 아닌 GitHub Actions의 runner를 사용하도록 변경
: https://prnd.slack.com/archives/C9UERACB1/p1743564034581079
- QA/Release 빌드는 runs-on을 8core의 Large runner를 사용하도록 변경
- Gradle/Java 설정 step 추가 
: GitHub-hosted runner는 이미 Android SDK가 설치되어 있음

HDA-16775 [공통] workflow - QA/Release 빌드 runs-on 분리

---

.github/workflows/build_qa.yml

- 필요할때만 QB실행하도록 QA/QB 빌드 workflow 분리 대응
- 필요할때만 QB실행하도록 QA/QB 빌드 분리 
: build_type을 전달받아서 맞는 빌드를 실행
: 기본으로 qa를 사용하도록 해서 입력하지 않아도 기본으로 QA빌드 하도록 처리
: comment남길때도 build_type에 맞게 댓글남기도록 처리

HDA-16787 [공통] workflow - build QB 별도로 만들기

---

.github/workflows/build_qa.yml
.github/workflows/build_release.yml

- large runner를 이용해서 keystore를 decode할때 오류 발생
: https://github.com/PRNDcompany/heydealer-android/actions/runs/14235337332/job/39893553608 
- 정확한 원인은 모르겠으나 self host와 github action runner의 플랫폼 차이 인것 같음
- 명확하게 따옴표(“) 추가하고 jks 파일 path로 설정해줘서 잘 동작하도록 처리

HDA-16795 [공통] workflow - keystore decode관련 코드 정정

---

.github/workflows/build_qa.yml

`build_qa.yml`의 concurrency group을 만들 때 `github.event.pull_request.number`와 `github.event.issue.number`가 둘 다 존재 하지 않아서 `issue_comment`가 트리거된 develop을 기준으로 만들어지게 됩니다.
기존에 `build.yml`을 호출하던 때에는 해당 job을 대상으로 concurrency group이 생성되었습니다.
이전처럼 `build` job을 대상으로 concurrency group을 생성하도록 변경합니다.
https://github.com/PRNDcompany/heydealer-call-android/actions/runs/14509096374

HDA-16957 [workflow] QA 빌드 동시성 오류 수정
