PRNDcompany/prnd-android-workflows

- .github/workflows/release_pr_create.yml
Release PR을 생성하는 workflow를 재사용하기 위한 reusable workflow를 추가합니다.
https://github.com/PRNDcompany/heydealer-android/pull/4093
> HDA-6870 [공통] [workflow 재사용] release PR 생성 [skip-ci]

- .github/workflows/release_pr_update.yml
재사용 가능한 release PR 업데이트 workflow를 추가합니다.
https://github.com/PRNDcompany/heydealer-android/pull/4107/checks
> HDA-6871 [공통] [workflow 재사용] release PR 업데이트

- .github/workflows/build_release_app.yml
release용 apk, aab를 빌드하는 workflow를 추가합니다.
> HDA-7433 [공통][GitHub Action 마이그레이션] release 빌드

- .github/workflows/build_qa_app.yml
qa용 apk를 생성하는 workflow를 추가합니다.
> HDA-7434 [공통][GitHub Action 마이그레이션] qa 빌드

- .github/workflows/jira_release.yml
> HDA-7972 [공통] jira_release 정규식 수정

- .github/workflows/build_app.yml
환경변수로 넘기고 받는 대신에 Task의 매개변수로 넘기고 받는 방식으로 변경합니다.
https://github.com/PRNDcompany/prnd-android-library/pull/1702#discussion_r1050490499
> HDA-7998 [공통][GitHub Action 마이그레이션] 환경변수 대신 매개변수로 받아서 처리

- .github/workflows/build_app.yml
> HDA-8037 [공통][GitHub Action 마이그레이션 2차] buildApp Task의 매개변수 이름을 camelCase로 변경

- .github/workflows/build_app.yml
- .github/workflows/check_skip.yml
- .github/workflows/unit_test.yml
PR 제목에 `[skip-ci]` 또는 `[skip ci]`가 포함되어 있으면 넘어가는 `check_skip` workflow를 추가합니다.
그리고 단위 테스트와 앱 빌드 workflow에 `check_skip` 단계를 추가합니다.
https://github.com/PRNDcompany/heydealer-call-android/pull/243
> HDA-8006 [공통][GitHub Action 마이그레이션 2차] PR 제목에 skip-ci 가 있으면 무시

- .github/workflows/check_skip.yml
PR title을 체크하는 대신 draft 여부를 체크하도록 변경합니다.
- Draft PR skip: https://github.com/PRNDcompany/heydealer-call-android/actions/runs/4121754329/jobs/7117749863
- PR 트리거로 앱 빌드: https://github.com/PRNDcompany/heydealer-call-android/actions/runs/4121758065/jobs/7117759664
> HDA-8070 [공통][GitHub Action 마이그레이션 2차] skip 기능을 draft PR 일 때 skip하는 방식으로 변경

- .github/workflows/release_pr_create.yml
Reverts PRNDcompany/prnd-android-workflows#24
> Revert "HDA-8840 [공통] [GitHub Action] release_pr_create 에서 pr_assignee 제거"

- .github/workflows/release_branch.yml
1. Dependencies.kt 에서 versionCode를 추출후 +1 해서 새로운 versionCode 생성
2. versionCode와 versionName을 환경변수에 등록
3. Dependencies.kt 파일에 versionCode/versionName 코드내용을 변경
4. commit & push
> HDA-8843 [공통] Release/Hotfix 버전 업데이트하는 GitHub Action 만들기

- .github/auto_assign.yml
prnd-android-workflows 저장소에 자동 assign 기능을 추가합니다.
> HDA-10262 prnd-android-workflows 저장소에 자동 assign 기능 추가

- .github/workflows/build.yml
- .github/workflows/build_app_by_comment.yml
- 기존 build_app.xml 파일 기반에서
- build_type에 따라서 맞는 gradlew 빌드를 실행하도록 처리
> HDA-10519 [공통][Jenkins -> GitHub Actions 마이그레이션] buildType을 받아서 해당하는 빌드 처리

- .github/workflows/build_app_by_comment.yml
- .github/workflows/move_s3_qa.yml
- .github/workflows/move_s3_release.yml
- QA/Release 빌드가 실행되면 결과물 파일을 S3의 tmp폴더에 업로드 해놓고 있는데
- 해당하는 workflow에서 tmp폴더에 있는 파일들을 각각에 맞는 S3의 위치로 이동시키는 workflow 추가
- https://github.com/PRNDcompany/heydealer-call-android/pull/330
> HDA-10747 [공통] S3 임시폴더에 업로드된 파일을 -> PR/Release 에 맞는 폴더로 이동

- .github/workflows/build_app_by_comment.yml
- .github/workflows/move_s3_qa.yml
- .github/workflows/move_s3_release.yml
- .github/workflows/output_path_comment.yml
- 결과물 파일 경로를 댓글로 추가하는 workflow 추가
- QA빌드 완료시 결과물 댓글 남기도록 추가
- 이전 PR에서 작업했던 내용에 오타가 있어서 함께 포함해서 fix: b65923f712e9237e228d4294ce37b4715746c512
> HDA-10524 [공통][Jenkins -> GitHub Actions 마이그레이션] QA, Release 빌드시 빌드파일 생성완료 PR comment 추가

- .github/workflows/move_s3_release.yml
- move_s3_qa → move_s3_release
> HDA-10868 [공통] release APK파일을 이동시키는 workflow에 잘못기재되어 있는 job이름 fix

- .github/workflows/build.yml
- build후 작업으로 추가적인 task를 실행하고 싶은 경우를 위한 지원기능 추가
- 고객용앱에서만 liapp task를 돌리기 위함
> HDA-11017 [공통] [workflow] build.yml에 추가 task를 실행할 수 있도록 지원

- .github/workflows/build.yml
- https://github.com/PRNDcompany/prnd-android-workflows/pull/55 에 이은 추가 개선
-  추가 task실행시에도 env설정 추가
> HDA-11017 [공통] [workflow] build.yml에 추가 task를 실행할 수 있도록 지원 - 추가개선

- .github/workflows/compare_jira_release_by_release_pr.yml
- 일부 Jira 번호들이 제대로 정규식으로 처리되지 않는 문제 해결버전 적용
- 아래 내용이 fix된 버전
: https://prnd.slack.com/archives/C9UERACB1/p1703208619115029
> HDA-11296 [공통] [workflow] Release에 배포예정인 Jira이슈 검증 workflow 버전 최신화

- .github/workflows/build.yml
debug 빌드에서는 clean하지 않도록 변경합니다.
https://prnd.slack.com/archives/C9UERACB1/p1706777738778409
> HDA-11863 [공통] debug 빌드에서 clean하지 않도록 변경

- .github/workflows/jira_release.yml
- https://github.com/PRNDcompany/jira-release/pull/10 작업이 반영된 버전 사용
> HDA-13783 [라이브러리] [workflow] jira release 버전 최신화

- .github/workflows/build.yml
https://prnd.slack.com/archives/C9UERACB1/p1724128473694819
> HDA-14345 [공통] debug 빌드에서 clean 하도록 변경

- .github/workflows/build.yml
Reverts PRNDcompany/prnd-android-workflows#66
> Revert "HDA-14345 [공통] debug 빌드에서 clean 하도록 변경"

- .github/workflows/release_pr_create.yml
GITHUB_ENV → GITHUB_OUTPUT
https://prnd.slack.com/archives/C9UERACB1/p1724825334561079
> HDA-14463 [workflow] Release PR생성시 branch이름 추출후 assign 로직 fix

- .github/workflows/release_branch.yml
메인 언어가 kotlin이므로 buildSrc의 소스 디렉토리도 kotlin으로 변경합니다.
> HDA-14531 [공통] buildSrc의 소스 디렉토리를 java에서 kotlin으로 변경

- .github/workflows/build.yml
- .github/workflows/build_qa.yml
https://github.com/PRNDcompany/prnd-android-library/pull/2936
> HDA-15995 [공통] QA 빌드에서 피쳐 테스트 서버가 표시되지 않는 버그 수정

- .github/workflows/build_qa.yml
- https://github.com/PRNDcompany/prnd-android-workflows/pull/82 에 보충하는 작업
- build 이름으로 변경된것에 맞게 대응 추가
> HDA-16794 [공통] workflow - 빌드관련 job의 이름을 모두 build로 통일 - fix

- .github/workflows/build_qa.yml
- local host 사양이 좋아져서 부담이 덜해지는것 같아서 QA/QB 빌드는 다시 local host를 사용하도록 변경
> HDA-16903 [공통] workflow - QA/QB빌드 local host로 사용하도록 변경
